# Generated by Django 3.1.2 on 2020-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0002_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.CharField(max_length=200),
        ),
    ]
